//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelArtScaling {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixelArtScaling.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap App {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("App", resourceCulture); }
        }
        internal static System.Drawing.Bitmap Width {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Width", resourceCulture); }
        }
        internal static System.Drawing.Bitmap Height {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Height", resourceCulture); }
        }
        internal static System.Drawing.Bitmap Resize {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Resize", resourceCulture); }
        }
        internal static System.Drawing.Bitmap Switch {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Switch", resourceCulture); }
        }
        internal static System.Drawing.Bitmap Repeat {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Repeat", resourceCulture); }
        }
        internal static System.Drawing.Bitmap Horizontal {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Horizontal", resourceCulture); }
        }
        internal static System.Drawing.Bitmap Vertical {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Vertical", resourceCulture); }
        }
        internal static System.Drawing.Bitmap ProgressCircularBlue {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("ProgressCircularBlue", resourceCulture); }
        }
        internal static System.Drawing.Bitmap Clipboard {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("Clipboard", resourceCulture); }
        }
    }
}
