//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageResizer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageResizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ========================================================================
        ///   ** {appname} v{version}, {copyright}
        ///   Version for Windows NT/9x/2000/XP/Vista/7  (All rights reserved)
        ///------------------------------------------------------------------------
        ///   This program is free software: you can redistribute it and/or modify
        ///   it under the terms of the GNU General Public License as published by
        ///   the Free Software Foundation, either version 3 of the License, or
        ///   (at your option) any later version. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CLIHelpText {
            get {
                return ResourceManager.GetString("CLIHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Height {
            get {
                object obj = ResourceManager.GetObject("Height", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Horizontal {
            get {
                object obj = ResourceManager.GetObject("Horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProgressCircularBlue {
            get {
                object obj = ResourceManager.GetObject("ProgressCircularBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Repeat {
            get {
                object obj = ResourceManager.GetObject("Repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Resize {
            get {
                object obj = ResourceManager.GetObject("Resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Switch {
            get {
                object obj = ResourceManager.GetObject("Switch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load ähnelt.
        /// </summary>
        internal static string ttCouldNotLoadImage {
            get {
                return ResourceManager.GetString("ttCouldNotLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value too small ähnelt.
        /// </summary>
        internal static string ttNeedWidthAndHeightAboveZero {
            get {
                return ResourceManager.GetString("ttNeedWidthAndHeightAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JPEG Encoder missing ähnelt.
        /// </summary>
        internal static string ttNoJpegSupport {
            get {
                return ResourceManager.GetString("ttNoJpegSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No script ähnelt.
        /// </summary>
        internal static string ttNoScriptToSave {
            get {
                return ResourceManager.GetString("ttNoScriptToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No image ähnelt.
        /// </summary>
        internal static string ttNothingToResize {
            get {
                return ResourceManager.GetString("ttNothingToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No image ähnelt.
        /// </summary>
        internal static string ttNothingToSave {
            get {
                return ResourceManager.GetString("ttNothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown filter ähnelt.
        /// </summary>
        internal static string ttUnknownFilter {
            get {
                return ResourceManager.GetString("ttUnknownFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load {0}\r\n\r\n{1} ähnelt.
        /// </summary>
        internal static string txCouldNotLoadImage {
            get {
                return ResourceManager.GetString("txCouldNotLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Need a width and height &gt; 0 to apply interpolation. ähnelt.
        /// </summary>
        internal static string txNeedWidthAndHeightAboveZero {
            get {
                return ResourceManager.GetString("txNeedWidthAndHeightAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System has no support to save as JPEG ! ähnelt.
        /// </summary>
        internal static string txNoJpegSupport {
            get {
                return ResourceManager.GetString("txNoJpegSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no script to save. ähnelt.
        /// </summary>
        internal static string txNoScriptToSave {
            get {
                return ResourceManager.GetString("txNoScriptToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to resize file: there is nothing to resize! ähnelt.
        /// </summary>
        internal static string txNothingToResize {
            get {
                return ResourceManager.GetString("txNothingToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is nothing to save. ähnelt.
        /// </summary>
        internal static string txNothingToSave {
            get {
                return ResourceManager.GetString("txNothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to resize file: there is no filter named &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string txUnknownFilter {
            get {
                return ResourceManager.GetString("txUnknownFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://code.google.com/p/2dimagefilter/ ähnelt.
        /// </summary>
        internal static string urlProject {
            get {
                return ResourceManager.GetString("urlProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://code.google.com/p/2dimagefilter/w/list ähnelt.
        /// </summary>
        internal static string urlWiki {
            get {
                return ResourceManager.GetString("urlWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vertical {
            get {
                object obj = ResourceManager.GetObject("Vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Width {
            get {
                object obj = ResourceManager.GetObject("Width", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
