//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageResizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageResizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Height {
            get {
                object obj = ResourceManager.GetObject("Height", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Horizontal {
            get {
                object obj = ResourceManager.GetObject("Horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProgressCircularBlue {
            get {
                object obj = ResourceManager.GetObject("ProgressCircularBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Repeat {
            get {
                object obj = ResourceManager.GetObject("Repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resize {
            get {
                object obj = ResourceManager.GetObject("Resize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Switch {
            get {
                object obj = ResourceManager.GetObject("Switch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        internal static string ttCouldNotLoadImage {
            get {
                return ResourceManager.GetString("ttCouldNotLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value too small.
        /// </summary>
        internal static string ttNeedWidthAndHeightAboveZero {
            get {
                return ResourceManager.GetString("ttNeedWidthAndHeightAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Encoder missing.
        /// </summary>
        internal static string ttNoJpegSupport {
            get {
                return ResourceManager.GetString("ttNoJpegSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image.
        /// </summary>
        internal static string ttNothingToResize {
            get {
                return ResourceManager.GetString("ttNothingToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image.
        /// </summary>
        internal static string ttNothingToSave {
            get {
                return ResourceManager.GetString("ttNothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ttUnknownFilter {
            get {
                return ResourceManager.GetString("ttUnknownFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load {0}\r\n\r\n{1}.
        /// </summary>
        internal static string txCouldNotLoadImage {
            get {
                return ResourceManager.GetString("txCouldNotLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a width and height &gt; 0 to apply interpolation..
        /// </summary>
        internal static string txNeedWidthAndHeightAboveZero {
            get {
                return ResourceManager.GetString("txNeedWidthAndHeightAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System has no support to save as JPEG !.
        /// </summary>
        internal static string txNoJpegSupport {
            get {
                return ResourceManager.GetString("txNoJpegSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resize file: there is nothing to resize!.
        /// </summary>
        internal static string txNothingToResize {
            get {
                return ResourceManager.GetString("txNothingToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to save..
        /// </summary>
        internal static string txNothingToSave {
            get {
                return ResourceManager.GetString("txNothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resize file: there is no filter named &apos;{0}&apos;.
        /// </summary>
        internal static string txUnknownFilter {
            get {
                return ResourceManager.GetString("txUnknownFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Vertical {
            get {
                object obj = ResourceManager.GetObject("Vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Width {
            get {
                object obj = ResourceManager.GetObject("Width", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
